### ISSUE TITLE
Error: Returned error: handle request error

### ISSUE THREAD

**Issue by CValeron** [node-real/js-direct-route#16]
Hi,

I was using direct-route without any problem. However, I have started to get below error during transaction.

Error: Returned error: handle request error
    at Object.ErrorResponse (/home/ec2-user/node_modules/@node-real/web3-core-helpers/lib/errors.js:29:19)
    at /home/ec2-user/node_modules/@node-real/web3-core-requestmanager/lib/index.js:302:36
    at XMLHttpRequest.request.onreadystatechange (/home/ec2-user/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/ec2-user/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/ec2-user/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/ec2-user/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/ec2-user/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    
    Any solution for this problem ?

**Comment by CValeron** [comment]
I recive code: -32603

**Comment by David-Guo** [comment]
get the same error code -32603

**Comment by Kevin-k-NR** [comment]
is working fine now
